name: Extract Windows and macOS fonts
on: push

jobs:
  extract-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          sudo apt-get install -y wimtools curl p7zip-full
          npm i playwright-chromium
      - name: Fetch Windows 10 ISO
        run: |
          LINK=$(node link.js win10)
          echo "Downloading Windows 10 ISO from link: ${LINK}"
          curl -sLf "${LINK}" -o win10.iso
          ls -lha win10.iso
      - name: Fetch Windows 11 ISO
        run: |
          LINK=$(node link.js win11)
          echo "Downloading Windows 11 ISO from link: ${LINK}"
          curl -sLf "${LINK}" -o win11.iso
          ls -lha win11.iso
      - name: Fetch macOS ISO
        run: |
          curl -sLf "https://raw.githubusercontent.com/acidanthera/OpenCorePkg/master/Utilities/macrecovery/macrecovery.py" -o macrecovery.py
          python macrecovery.py download
          ls -lha BaseSystem.dmg
      - name: Extract Windows fonts
        run: |
          mkdir mount
          sudo mount win10.iso mount -o loop,ro
          wimextract mount/sources/install.wim 1 /Windows/Fonts/"*".{ttf,ttc} --dest-dir fonts-win-10
          sudo umount mount
          sudo mount win11.iso mount -o loop,ro
          wimextract mount/sources/install.wim 1 /Windows/Fonts/"*".{ttf,ttc} --dest-dir fonts-win-11
          sudo umount mount
      - name: Extract macOS fonts
        run: |
          7z e BaseSystem.dmg -ofonts-mac "*.ttf" "*.ttc" -r
      - name: Upload Windows 10 fonts artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows 10 fonts
          path: fonts-win-10/
      - name: Upload Windows 11 fonts artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows 11 fonts
          path: fonts-win-11/
      - name: Upload macOS fonts artifact
        uses: actions/upload-artifact@v2
        with:
          name: macOS fonts
          path: fonts-mac/
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            fonts-win-10/
            fonts-win-11/
            fonts-mac/
