name: Extract Windows and macOS fonts
on: [push, pull_request]

jobs:
  extract-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          curl -sL https://deb.nodesource.com/setup_15.x | sudo -E bash -
          sudo apt-get install -y nodejs wimtools curl p7zip-full python
          npm i playwright-chromium
      - name: Fetch Windows ISO
        run: |
          LINK=$(node link.js)
          echo "Downloading Windows 10 ISO from link: ${LINK}"
          curl -s "${LINK}" -o win10.iso
          ls -lha win10.iso
      - name: Fetch macOS ISO
        run: |
          curl -s "https://raw.githubusercontent.com/acidanthera/OpenCorePkg/master/Utilities/macrecovery/macrecovery.py" -o macrecovery.py
          python macrecovery.py download
          ls -lha BaseSystem.dmg
      - name: Extract fonts
        run: |
          mkdir mount
          sudo mount win10.iso mount -o loop,ro
          wimextract mount/sources/install.wim 1 /Windows/{Fonts/"*".{ttf,ttc},System32/Licenses/neutral/"*"/"*"/license.rtf} --dest-dir fonts-win
          sudo umount mount
          7z e BaseSystem.dmg -ofonts-mac '*.ttf' -r
          7z a fonts-mac.zip fonts-mac/*
          7z a fonts-win.zip fonts-win/*
#      - name: Upload Windows fonts artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: Windows fonts
#          path: fonts-win/
#      - name: Upload macOS fonts artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: macOS fonts
#          path: fonts-mac/
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }} # create tag with incrementing number
          release_name: Extracted fonts - commit ${{ github.sha }}
      - name: Upload Windows fonts to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./fonts-win.zip
          asset_name: Windows-fonts.zip
          asset_content_type: application/zip
      - name: Upload macOS fonts to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./fonts-mac.zip
          asset_name: macOS-fonts.zip
          asset_content_type: application/zip
      - name: Clean up
        run: |
          rm -rf node_modules/ win10.iso BaseSystem.dmg fonts-win/ fonts-mac/ mount/
